title: derflo
email: website@flowinho.com
description: >-
  Alle Inhalte auf dieser Website sind den Menschen gewidmet, die mein Leben lebenswert machen und meinem Alltag Bedeutung, Liebe und Sinn geben: meinen Töchtern, meiner Partnerin, 
  meinen Freunden und meiner Familie. Die hier wiedergegebenen Meinungen sind Momentaufnahmen und spiegeln unter Umständen nicht meine aktuellen Ansichten wieder. 
  Ich schreibe hier nicht im Auftrag meiner Arbeitgeber.
baseurl: "" 
url: "" 

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /blog/:year/:title/

# Minima settings
header_pages:
  - about.md
  - images.md

# This is to disable Rouge, Jekylls default syntax highlighter on GitHub Pages
show_excerpts: true
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true